name: Trigger docs release in Stoplight
on: push
jobs:
  docs-list:
    runs-on: ubuntu-latest
    steps:
    - name: curl request
      env:
        # TOKEN: ${{ secrets.SOME_TOKEN }}
        TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzdG9wbGlnaHR8NTkzIiwidXNlcm5hbWUiOiJwenVyZWsiLCJlbWFpbCI6InAuenVyZWtAZ21haWwuY29tIiwibmFtZSI6IlBpb3RyIFp1cmVrIiwiaWF0IjoxNTY2MjkxNTMwLCJrZXkiOiI4U1JwSlN1MUJ1dHdpdXhUdjl1RiJ9.ncZFT7O4QTs3bdqdto1FZr1FkmpOv_10eVZVYZV7krw
        URL: https://next-api.stoplight.io/projects/17493
      run: 'curl -H "Authorization: Bearer $TOKEN" $URL'


# on: push
# name: Trigger docs release in Stoplight
# jobs:
#   docs-list:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: curl request
#         env:
#           STOPLIGHT_DOMAIN: docs.vendhq.com
#           STOPLIGHT_TOKEN: ${{ secrets.STOPLIGHT_TOKEN }}
#           STOPLIGHT_URL: https://next-api.stoplight.io/projects/17493
#         run: curl "-H Authorization: Bearer $STOPLIGHT_TOKEN $STOPLIGHT_URL"
#   docs-release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: curl request
#         uses: actions/bin/curl@master
#         env:
#           DOMAIN: docs.vendhq.com
#           TOKEN: ${{ secrets.STOPLIGHT_TOKEN }}
#           URL: https://next-api.stoplight.io/docs.release
#         with:
#           args: "-H Authorization: Bearer $TOKEN $URL?domain=$DOMAIN"
#           # args: "-H" "Content-Type: application/json;charset=UTF-8" "-H" "Authorization: Bearer $TOKEN" "--data-binary" '{ "setLive": true }' "$URL?domain=$DOMAIN" "--compressed"
