name: Trigger docs release in Stoplight
on:
  push:
    branches:
    - master
jobs:
  docs-release:
    runs-on: ubuntu-latest
    steps:
    - name: curl request
      env:
        DOMAIN: docs.vendhq.com
        TOKEN: ${{ secrets.STOPLIGHT_TOKEN }}
        URL: https://next-api.stoplight.io/docs.release
      run: >-
        curl -H "Content-Type: application/json;charset=UTF-8" -H "Authorization: Bearer $TOKEN" --data-binary '{"setLive": true}' $URL?domain=$DOMAIN --compressed
