on: push
name: Trigger docs release in Stoplight
jobs:
  docs-list:
    runs-on: ubuntu-latest
    steps:
      - name: curl request
        env:
          STOPLIGHT_DOMAIN: docs.vendhq.com
          STOPLIGHT_TOKEN: ${{ secrets.STOPLIGHT_TOKEN }}
          STOPLIGHT_URL: https://next-api.stoplight.io/projects/17493
        run: curl -H "Authorization: Bearer $STOPLIGHT_TOKEN" $STOPLIGHT_URL
  docs-release:
    runs-on: ubuntu-latest
    steps:
      - name: curl request
        uses: actions/bin/curl@master
        env:
          STOPLIGHT_DOMAIN: docs.vendhq.com
          STOPLIGHT_TOKEN: ${{ secrets.STOPLIGHT_TOKEN }}
          STOPLIGHT_URL: https://next-api.stoplight.io/docs.release
        with:
          args: "-H Authorization: Bearer $STOPLIGHT_TOKEN $STOPLIGHT_URL?domain=$STOPLIGHT_DOMAIN"
          # args: "-H" "Content-Type: application/json;charset=UTF-8" "-H" "Authorization: Bearer $STOPLIGHT_TOKEN" "--data-binary" '{ "setLive": true }' "$STOPLIGHT_URL?domain=$STOPLIGHT_DOMAIN" "--compressed"
